services:
  agent:
    build: { context: agent }
    volumes:
      - .:/workspaces/assistant_agent:cached
    ports:
      - 8000:8000
    command: sleep infinity

  chatbot:
    build: { context: chatbot }
    volumes:
      - chatbot_data:/app/backend/data:cached
    ports:
      - 8001:8080

volumes:
  chatbot_data: