services:
  agent:
    profiles: ["dev"]
    build:
      context: agent
      target: dev
    volumes:
      - .:/workspaces/assistant_agent:cached
    ports:
      - 8000:8000
    command: sleep infinity

  agent-rune:
    profiles: ["prod"]
    build:
      context: agent
      target: prod
    environment:
      - AA_AGENT_MODULE=rune
      - AA_DISCORD_BOT_TOKEN=$AA_DISCORD_BOT_TOKEN_1
    env_file:
      - agent/.env
    ports:
      - 8002:8000

  agent-holo:
    profiles: ["prod"]
    build:
      context: agent
      target: prod
    environment:
      - AA_AGENT_MODULE=holo
      - AA_DISCORD_BOT_TOKEN=$AA_DISCORD_BOT_TOKEN_2
    env_file:
      - agent/.env
    ports:
      - 8003:8000

  chatbot:
    build: { context: chatbot }
    volumes:
      - chatbot_data:/app/backend/data:cached
    ports:
      - 8001:8080

volumes:
  chatbot_data: