[project]
name = "assistant_agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "namoshika", email = "namoshika@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "duckdb-engine>=0.17.0",
    "fastapi[standard]>=0.135.3",
    "langchain>=1.2.13",
    "langchain-aws>=1.4.1",
    "langchain-google-genai>=4.2.1",
    "langchain-postgres>=0.0.17",
    "llama-index>=0.14.18",
    "llama-index-embeddings-databricks>=0.5.1",
    "llama-index-embeddings-google-genai>=0.5.0",
    "llama-index-llms-google-genai>=0.8.7",
    "llama-index-storage-docstore-duckdb>=0.3.0",
    "llama-index-storage-docstore-postgres>=0.5.0",
    "llama-index-vector-stores-duckdb>=0.6.0",
    "llama-index-vector-stores-postgres>=0.8.1",
    "mlflow>=3.11.1",
    "obsidianmd-parser>=0.4.0",
    "sqlalchemy>=2.0.48",
]

[project.optional-dependencies]
vsc = [
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
markers = [
    "integration: 実際の外部システム (PostgreSQL, Gemini API) を必要とするテスト",
]
env_files = [".env"]

[tool.fastapi]
entrypoint = "assistant_agent.agent_server:app"

[tool.ruff]
extend-exclude = ["scripts/*.ipynb", "docs"]
line-length = 100

[tool.ruff.lint]
extend-select = ["D", "E", "F", "I", "N", "W"]
ignore = ["D100", "D101", "D104", "D203", "D213"]

[dependency-groups]
dev = [
    "boto3>=1.42.63",
    "ipykernel>=7.3.0",
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "pytest-dotenv>=0.5.2",
    "pytest-mock>=3.15.1",
    "ruff>=0.15.7",
]
